# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cars.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QMainWindow,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_closevideo(object):
    def setupUi(self, closevideo):
        if not closevideo.objectName():
            closevideo.setObjectName(u"closevideo")
        closevideo.resize(1268, 769)
        closevideo.setStyleSheet(u"background-color: rgb(192, 255, 255);")
        self.centralwidget = QWidget(closevideo)
        self.centralwidget.setObjectName(u"centralwidget")
        self.video = QLabel(self.centralwidget)
        self.video.setObjectName(u"video")
        self.video.setGeometry(QRect(230, 120, 541, 421))
        self.video.setStyleSheet(u"background-color: rgb(181, 255, 183);")
        self.video.setScaledContents(True)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(790, 120, 321, 161))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 30, 61, 31))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.car = QLabel(self.groupBox)
        self.car.setObjectName(u"car")
        self.car.setGeometry(QRect(90, 30, 61, 31))
        self.car.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 80, 61, 31))
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.van = QLabel(self.groupBox)
        self.van.setObjectName(u"van")
        self.van.setGeometry(QRect(90, 80, 61, 31))
        self.van.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(170, 30, 61, 31))
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(170, 80, 61, 31))
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.truck = QLabel(self.groupBox)
        self.truck.setObjectName(u"truck")
        self.truck.setGeometry(QRect(230, 80, 61, 31))
        self.truck.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bus = QLabel(self.groupBox)
        self.bus.setObjectName(u"bus")
        self.bus.setGeometry(QRect(240, 30, 61, 31))
        self.bus.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 120, 61, 31))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.grade = QLabel(self.groupBox)
        self.grade.setObjectName(u"grade")
        self.grade.setGeometry(QRect(90, 120, 61, 31))
        self.grade.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 20, 871, 81))
        font = QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet(u"\n"
"background-color: rgb(233, 255, 250);")
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(230, 550, 541, 151))
        self.plainTextEdit = QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(13, 23, 521, 121))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(790, 300, 321, 401))
        self.openpicture = QPushButton(self.groupBox_3)
        self.openpicture.setObjectName(u"openpicture")
        self.openpicture.setGeometry(QRect(20, 170, 111, 51))
        self.openpicture.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.opencap = QPushButton(self.groupBox_3)
        self.opencap.setObjectName(u"opencap")
        self.opencap.setGeometry(QRect(180, 160, 111, 51))
        self.opencap.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.openvideo = QPushButton(self.groupBox_3)
        self.openvideo.setObjectName(u"openvideo")
        self.openvideo.setGeometry(QRect(20, 240, 111, 51))
        self.openvideo.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.closecap = QPushButton(self.groupBox_3)
        self.closecap.setObjectName(u"closecap")
        self.closecap.setGeometry(QRect(180, 240, 111, 51))
        self.closecap.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.save = QPushButton(self.groupBox_3)
        self.save.setObjectName(u"save")
        self.save.setGeometry(QRect(20, 320, 111, 51))
        self.save.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.exit = QPushButton(self.groupBox_3)
        self.exit.setObjectName(u"exit")
        self.exit.setGeometry(QRect(180, 320, 111, 51))
        self.exit.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"")
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 30, 61, 31))
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.conf = QLabel(self.groupBox_3)
        self.conf.setObjectName(u"conf")
        self.conf.setGeometry(QRect(80, 30, 61, 31))
        self.conf.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 120, 61, 31))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 70, 51, 31))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.xmin = QLabel(self.groupBox_3)
        self.xmin.setObjectName(u"xmin")
        self.xmin.setGeometry(QRect(80, 70, 61, 31))
        self.xmin.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.xmax = QLabel(self.groupBox_3)
        self.xmax.setObjectName(u"xmax")
        self.xmax.setGeometry(QRect(90, 120, 61, 31))
        self.xmax.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ymin_2 = QLabel(self.groupBox_3)
        self.ymin_2.setObjectName(u"ymin_2")
        self.ymin_2.setGeometry(QRect(160, 70, 61, 31))
        self.ymin_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ymin = QLabel(self.groupBox_3)
        self.ymin.setObjectName(u"ymin")
        self.ymin.setGeometry(QRect(220, 70, 61, 31))
        self.ymin.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(160, 120, 61, 31))
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ymax = QLabel(self.groupBox_3)
        self.ymax.setObjectName(u"ymax")
        self.ymax.setGeometry(QRect(220, 120, 61, 31))
        self.ymax.setAlignment(Qt.AlignmentFlag.AlignCenter)
        closevideo.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(closevideo)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1268, 33))
        closevideo.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(closevideo)
        self.statusbar.setObjectName(u"statusbar")
        closevideo.setStatusBar(self.statusbar)

        self.retranslateUi(closevideo)

        QMetaObject.connectSlotsByName(closevideo)
    # setupUi

    def retranslateUi(self, closevideo):
        closevideo.setWindowTitle(QCoreApplication.translate("closevideo", u"MainWindow", None))
        self.video.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("closevideo", u"\u7edf\u8ba1", None))
        self.label_5.setText(QCoreApplication.translate("closevideo", u"\u8f7f\u8f66\u6570\u91cf\uff1a", None))
        self.car.setText("")
        self.label_9.setText(QCoreApplication.translate("closevideo", u"\u9762\u5305\u8f66\u6570\u91cf\uff1a", None))
        self.van.setText("")
        self.label_11.setText(QCoreApplication.translate("closevideo", u"\u516c\u4ea4\u8f66\u6570\u91cf:l", None))
        self.label_13.setText(QCoreApplication.translate("closevideo", u"\u5361\u8f66\u6570\u91cf\uff1a", None))
        self.truck.setText("")
        self.bus.setText("")
        self.label_4.setText(QCoreApplication.translate("closevideo", u"\u62e5\u5835\u60c5\u51b5\uff1a", None))
        self.grade.setText("")
        self.label.setText(QCoreApplication.translate("closevideo", u"\u57fa\u4e8eyolov8\u7684\u8f66\u6d41\u68c0\u6d4b\u7cfb\u7edf", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("closevideo", u"GroupBox", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("closevideo", u"\u64cd\u4f5c\u680f", None))
        self.openpicture.setText(QCoreApplication.translate("closevideo", u"\u6253\u5f00\u56fe\u7247", None))
        self.opencap.setText(QCoreApplication.translate("closevideo", u"\u6253\u5f00\u6444\u50cf\u5934", None))
        self.openvideo.setText(QCoreApplication.translate("closevideo", u"\u6253\u5f00\u89c6\u9891", None))
        self.closecap.setText(QCoreApplication.translate("closevideo", u"\u5173\u95ed\u6444\u50cf\u5934", None))
        self.save.setText(QCoreApplication.translate("closevideo", u"\u4fdd\u5b58", None))
        self.exit.setText(QCoreApplication.translate("closevideo", u"\u9000\u51fa", None))
        self.label_2.setText(QCoreApplication.translate("closevideo", u"conf\uff1a", None))
        self.conf.setText("")
        self.label_6.setText(QCoreApplication.translate("closevideo", u"xmax\uff1a", None))
        self.label_7.setText(QCoreApplication.translate("closevideo", u"xmin\uff1a", None))
        self.xmin.setText("")
        self.xmax.setText("")
        self.ymin_2.setText(QCoreApplication.translate("closevideo", u"ymin\uff1a", None))
        self.ymin.setText("")
        self.label_12.setText(QCoreApplication.translate("closevideo", u"ymax\uff1a", None))
        self.ymax.setText("")
    # retranslateUi

